### ISSUE TITLE
Question about other packages.

### ISSUE THREAD

**Issue by zhangjh915** [anibali/docker-pytorch#12]
Hi, thanks for the work for the docker image. I am kind of new to docker and wonder if there is a way to pip install other needed packages in this docker image, "matplotlib" for example? I tried to run "docker......pytorch /bin/bash" and pip install there. However, when I exit and coma back again it will  disappear. Need some help~

**Comment by anibali** [comment]
I recommend that you look up some Docker tutorials and familiarise yourself with how it works, since this is a very basic question.

One way of achieving what you want is to create your own Dockerfile based on mine using the `FROM` line. So with this approach you will have your own custom image with the additional packages you need.

Another option is to run a container, but not remove it when it stops (no `--rm` option). Then you can start/stop it by its name/ID whenever you want, maintaining its state. This can be useful for testing stuff out, but makes it more difficult to create more containers later.

**Comment by hakunin** [comment]
To the other newbies like me this is what I did:

1) download the dockerfile from here and
2) added requirements.txt near the end of the file as suggested [here](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
```
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
COPY . /tmp/
```
3) listed my packages in requirements like so
```
pandas
....
```

I used [this tutorial](https://takacsmark.com/dockerfile-tutorial-by-example-dockerfile-best-practices-2018/#1-create-the-dockerfile) to get oriented.
