### ISSUE TITLE
Upgrade Pytorch

### ISSUE THREAD

**Issue by Zethson** [anibali/docker-pytorch#22]
Pytorch 1.4 has been released. Would it be possibly to adapt the cuda 10 container to it?

**Comment by anibali** [comment]
As of https://github.com/anibali/docker-pytorch/commit/a4295e080457323353753ed7da25fcb73cd60f97, PyTorch 1.4.0 is now provided in `no-cuda`, `cuda-10.1`, and `cuda-9.2`. The images are still building on Docker Hub so it will probably be an hour or two until they are available to download.

**Comment by anibali** [comment]
The new images are now live.

**Comment by Zethson** [comment]
Thank you very much. Would it also be possible to switch to the 

`FROM nvidia/cuda:10.2-base-ubuntu18.04` base image?

Furthermore, could we upgrade python 3.6 to 3.7? 3.8 is not yet supported by Pytorch.

**Comment by anibali** [comment]
No, I'm hesitant to make changes that big until I have a better system for versioning Docker tags. a) I don't want to break things for people using these as base images, and b) I don't want things to become too unmanageable for myself to keep track of.

I'll probably reevaluate the situation again after Ubuntu 20.04 drops, because I do want to be able to update things more easily moving forward. In the meantime, feel free to just download the Dockerfile you like and tweak it---it should be as easy as just changing the version numbers (I use a bunch of 18.04-based images myself).

**Comment by Zethson** [comment]
All right!

**Comment by anibali** [comment]
@Zethson  I've overhauled the repo and added a few new images for PyTorch 1.5.0 which are based on Ubuntu 18.04. You might be interested in `anibali/pytorch:1.5.0-cuda10.2-ubuntu18.04`, which also uses Python 3.8. I plan on creating Ubuntu 20.04 variants too as soon as NVIDIA releases appropriate base images.

**Comment by Zethson** [comment]
Thank you very much!
