### ISSUE TITLE
Any ideas regarding reducing Image size?

### ISSUE THREAD

**Issue by IamGroot19** [anibali/docker-pytorch#29]
I am new to Docker & your project has helped me understand better about how to write Dockerfiles  (Thank you ^^).

You seem to using MiniConda for installing pytorch. But for my case, since I need more packages, installing a few more packages leads to a size of 5GB+. (Size of the docker-pytorch Image with Miniconda was already 3.5GB).

Is there anyway to reduce the sizes further? Would be very helpful if the size can be brought down to <2GB (since I have a bad internet connection with limited bandwidth). 

I read somewhere about Multi-Stage builds but was wondering if that could be used somehow here? Also, are there any other means through which I can achieve Image size reduction?

**Comment by anibali** [comment]
Multi-stage builds are useful for situations where you need to build software that is included in the image, since you can setup a development environment in one image, build the software there, then copy the built artifacts across to the actual final image, all in one Dockerfile. However, if you look at e.g. https://github.com/anibali/docker-pytorch/blob/master/dockerfiles/1.7.0-cuda11.0-ubuntu20.04/Dockerfile you'll notice that it just uses binaries and doesn't need to build anything. So I don't see a way of using multi-stage builds to reduce the size of the base docker-pytorch image. Perhaps it could be useful if any of the additional software you're adding requires building.

Unfortunately, I can't see much fat to cut at all from my base images---PyTorch and its dependencies are just really big. I suppose if you don't need torchvision you could cut that from the image yourself.
