### ISSUE TITLE
docker build fails for cuda 7.5

### ISSUE THREAD

**Issue by rkosti** [anibali/docker-pytorch#3]
Hi @anibali , 
When I try to build the docker image for CUDA 7.5, I get the following error for step 18/28:
```
EnvironmentLocationNotFound: Not a conda environment: /home/user/miniconda/envs/py36/envs/pytorch-py36
The command '/bin/sh -c conda install -y --name pytorch-py36 -c soumith     magma-cuda75  && conda clean -ya' returned a non-zero code: 1

```

Do you have a pre-built docker image somewhere stored or in the docker-hub? That should help avoid building from scratch.

**Comment by anibali** [comment]
https://github.com/anibali/docker-pytorch/commit/43b18fbbe325e641e3c68518f669a10527f6b5c1 should fix the issue. Since PyTorch is not built against CUDA 7.5 after v0.3.0, the cuda-7.5 image is [now fixed at that version](https://github.com/anibali/docker-pytorch/blob/43b18fbbe325e641e3c68518f669a10527f6b5c1/cuda-7.5/Dockerfile#L48-L52).

I've also set up automated builds over at https://hub.docker.com/r/anibali/pytorch/. I'm not sure how long it will take for the images to go live, they are currently in the process of building.

**Comment by rkosti** [comment]
I've checked automated builds and built it on my system as well, it works smoothly now.
Thanks for the fix.
