### ISSUE TITLE
CUDA Version Problem

### ISSUE THREAD

**Issue by ghost** [anibali/docker-pytorch#35]
I have install the cuda for version 11.4.0, and now i wonder know that could i use the cuda 11.3 dockerfile to build my docker container?

**Comment by anibali** [comment]
Yes, that should work just fine since the image contains a separate copy of CUDA (I am personally using a CUDA 11.3 image with CUDA 11.5 on my host at the moment). The only requirement is that the CUDA version in the Docker image is supported by your host NVIDIA driver version. So if, for example, your host was running an old driver (e.g. 418) you would not be able to use CUDA 11 (more info: https://docs.nvidia.com/deploy/cuda-compatibility/). This shouldn't be a problem for you.
